### ISSUE TITLE
Instead of randomly choosing an element to interact with, choose all possible elements

### ISSUE THREAD

**Issue by marco-c** [marco-c/autowebcompat#45]
Currently, we are choosing elements to interact with in a random fashion.
Instead, we should explore all possible paths (up to a maximum level that we need to decide).

**Comment by amit2rockon** [comment]
does it mean we have to interact with all elements which are present in the website and remove the use of random.shuffle(children) from collect.py?

**Comment by marco-c** [comment]
Yes, probably a depth-first search with a limit on the number of nodes (and instead of backtracking, restart from the beginning).

**Comment by sagarvijaygupta** [comment]
@marco-c  I wanted to work on this issue! What should be the maximum level?

**Comment by marco-c** [comment]
Currently it's 7, let's see if that works for this new approach too. Ideally define it in a global variable at the beginning of collect.py (e.g. `MAX_INTERACTION_DEPTH = 7`).

**Comment by sagarvijaygupta** [comment]
@marco-c I started working on this issue. 
According to the naming convention that is being followed it won't be possible to implement the given idea. 
Also the ```text file``` generated will have to be changed accordingly for a given ```bug```. 
 Any naming convention you would prefer? For the ```text file```  I was thinking to make it like a tree.
Something like this.
```
elem_attributes:
    elem_attributes:
          elem_attributes:
    elem_attributes:
          elem_attributes:
                elem_attributes:
          elem_attributes:
                elem_attributes:
                      elem_attributes:
```


 And naming convention for images to be of type ```WEBCOMPATID_lineNumberOfStep1_lineNumberOfStep2_lineNumberOfStep3_....._browser.png``` where ```lineNumber``` is the line number in the text file.
